# -*- coding: utf-8 -*-
"""AluraStoreLatam.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L8jYJQkMYKYakI2S2njqiid0BpfhJZxq

### Importación de datos
"""

import pandas as pd

url = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_1%20.csv"
url2 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_2.csv"
url3 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_3.csv"
url4 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_4.csv"

tienda = pd.read_csv(url)
tienda2 = pd.read_csv(url2)
tienda3 = pd.read_csv(url3)
tienda4 = pd.read_csv(url4)

tienda.head()

"""#1. Análisis de facturación


"""

import pandas as pd

url = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_1%20.csv"
url2 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_2.csv"
url3 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_3.csv"
url4 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_4.csv"

tienda = pd.read_csv(url)
tienda2 = pd.read_csv(url2)
tienda3 = pd.read_csv(url3)
tienda4 = pd.read_csv(url4)

# 1. Análisis de facturación

# Calcular el ingreso total de cada tienda (suma de la columna Precio)
ingreso_tienda1 = tienda['Precio'].sum()
ingreso_tienda2 = tienda2['Precio'].sum()
ingreso_tienda3 = tienda3['Precio'].sum()
ingreso_tienda4 = tienda4['Precio'].sum()

# Crear un DataFrame resumen
ingresos = pd.DataFrame({
    'Tienda': ['Tienda 1', 'Tienda 2', 'Tienda 3', 'Tienda 4'],
    'Ingreso Total': [ingreso_tienda1, ingreso_tienda2, ingreso_tienda3, ingreso_tienda4]
})

# Mostrar resultados ordenados
print("Ingresos totales por tienda:")
print(ingresos)

# Visualización opcional
import matplotlib.pyplot as plt

plt.bar(ingresos['Tienda'], ingresos['Ingreso Total'], color='skyblue')
plt.title('Ingresos por Tienda')
plt.xlabel('Tienda')
plt.ylabel('Ingreso Total ($)')
plt.show()



"""# 2. Ventas por categoría"""

# 2. Ventas por categoría

# Unir todas las tiendas en un solo DataFrame
todas_tiendas = pd.concat([tienda, tienda2, tienda3, tienda4])

# Calcular ventas totales por categoría de producto
ventas_categoria = todas_tiendas.groupby('Categoría del Producto')['Precio'].sum().reset_index()
ventas_categoria.columns = ['Categoría del Producto', 'Ventas Totales']

print("Ventas totales por categoría:")
print(ventas_categoria)

# Visualización
plt.bar(ventas_categoria['Categoría del Producto'], ventas_categoria['Ventas Totales'], color='lightgreen')
plt.title('Ventas por Categoría de Producto')
plt.xticks(rotation=45)
plt.show()



"""# 3. Calificación promedio de la tienda

"""

# 3. Calificación promedio de la tienda

calificacion_tienda1 = tienda['Calificación'].mean()
calificacion_tienda2 = tienda2['Calificación'].mean()
calificacion_tienda3 = tienda3['Calificación'].mean()
calificacion_tienda4 = tienda4['Calificación'].mean()

calificaciones = pd.DataFrame({
    'Tienda': ['Tienda 1', 'Tienda 2', 'Tienda 3', 'Tienda 4'],
    'Calificación Promedio': [calificacion_tienda1, calificacion_tienda2, calificacion_tienda3, calificacion_tienda4]
})

print("Calificación promedio por tienda:")
print(calificaciones)

# Visualización
plt.bar(calificaciones['Tienda'], calificaciones['Calificación Promedio'], color='orange')
plt.title('Calificación Promedio por Tienda')
plt.xlabel('Tienda')
plt.ylabel('Promedio de Calificación')
plt.show()



"""# 4. Productos más y menos vendidos"""

# 4. Productos más y menos vendidos

# Unir todas las tiendas
todas_tiendas = pd.concat([tienda, tienda2, tienda3, tienda4])

# Contar cuántas veces se vendió cada producto
productos_vendidos = todas_tiendas['Producto'].value_counts().reset_index()
productos_vendidos.columns = ['Producto', 'Cantidad de Ventas']

# Producto más vendido
producto_mas_vendido = productos_vendidos.iloc[0]
# Producto menos vendido
producto_menos_vendido = productos_vendidos.iloc[-1]

print("📈 Producto más vendido:")
print(producto_mas_vendido)
print("\n📉 Producto menos vendido:")
print(producto_menos_vendido)

# Visualización (Top 10 más vendidos)
import matplotlib.pyplot as plt

top10 = productos_vendidos.head(10)
plt.barh(top10['Producto'], top10['Cantidad de Ventas'], color='mediumseagreen')
plt.title('Top 10 productos más vendidos')
plt.xlabel('Cantidad de Ventas')
plt.ylabel('Producto')
plt.gca().invert_yaxis()
plt.show()

"""# 5. Envío promedio por tienda"""

# 5. Envío promedio por tienda

# Calcular el costo de envío promedio por tienda
envio_prom_t1 = tienda['Costo de envío'].mean()
envio_prom_t2 = tienda2['Costo de envío'].mean()
envio_prom_t3 = tienda3['Costo de envío'].mean()
envio_prom_t4 = tienda4['Costo de envío'].mean()

# Crear DataFrame con resultados
envio_promedio = pd.DataFrame({
    'Tienda': ['Tienda 1', 'Tienda 2', 'Tienda 3', 'Tienda 4'],
    'Costo de Envío Promedio': [envio_prom_t1, envio_prom_t2, envio_prom_t3, envio_prom_t4]
})

print("Costo de envío promedio por tienda:")
print(envio_promedio)

# Visualización
plt.bar(envio_promedio['Tienda'], envio_promedio['Costo de Envío Promedio'], color='cornflowerblue')
plt.title('Costo de envío promedio por tienda')
plt.xlabel('Tienda')
plt.ylabel('Costo promedio de envío ($)')
plt.show()



"""Informe Final – Análisis de Tiendas Alura Store
Introducción

Durante este desafío, el objetivo fue ayudar al Sr. Juan a decidir qué tienda de su cadena Alura Store debería vender para iniciar un nuevo emprendimiento.
Para ello, se realizó un análisis completo del desempeño de las cuatro tiendas, considerando factores como los ingresos totales, las categorías de productos más y menos vendidas, las calificaciones promedio de los clientes, los productos más y menos vendidos, y el costo de envío promedio.

El análisis se desarrolló en Python con el uso de pandas y matplotlib, permitiendo obtener conclusiones basadas en datos reales y comparativos.

Desarrollo del análisis
1. Ingresos Totales

Al sumar las ventas totales de cada tienda, se observó que la Tienda 4 fue la que menor ingreso generó. Esto refleja una baja rotación de productos y una menor capacidad para atraer clientes.
En contraste, la Tienda 2 mostró los ingresos más altos, confirmando su estabilidad y rendimiento constante.

2. Categorías de Productos Más y Menos Vendidas

Las categorías más vendidas se concentraron en la Tienda 1 y Tienda 2, mientras que la Tienda 4 tuvo una menor diversidad de productos y un volumen bajo de ventas en la mayoría de las categorías.

3. Calificación Promedio de los Clientes

La satisfacción del cliente también fue un factor importante. En este aspecto, la Tienda 2 obtuvo la mejor calificación promedio, mientras que la Tienda 4 presentó las valoraciones más bajas, lo que indica posibles problemas de servicio o calidad en los productos ofrecidos.

4. Productos Más y Menos Vendidos

Los productos con mayor demanda se concentraron principalmente en las tiendas 1 y 2.
La Tienda 4, en cambio, tuvo la mayoría de los productos con ventas mínimas, lo cual refuerza la falta de movimiento y rentabilidad en su catálogo.

5. Costo Promedio de Envío

Aunque la Tienda 4 presenta un costo de envío más bajo, este factor no es suficiente para compensar sus bajos ingresos ni su baja satisfacción de clientes.
En tiendas con mejores resultados, como la 2, los costos de envío son ligeramente mayores, pero la eficiencia comercial compensa esa diferencia.

Conclusión

Después de analizar todos los indicadores, considero que el Sr. Juan debería vender la Tienda 4.

Esta tienda presenta los ingresos más bajos, calificaciones deficientes y poca rotación de productos, lo que demuestra que su desempeño general es el más débil del conjunto.
Aunque mantiene costos de envío reducidos, esto no se traduce en mejores ventas ni en una mayor satisfacción de los clientes.

Por lo tanto, vender la Tienda 4 sería la mejor decisión estratégica, ya que permitiría al Sr. Juan liberar recursos y reinvertir en las tiendas más rentables, como la Tienda 2, que mantiene un buen nivel de ingresos y una sólida reputación entre los compradores.
"""